services:

  # ASP.NET Core Web API Application
  student_management_api:
    container_name: api_container
    ports:
      - "5000:5000"
    depends_on:
      - student_management_postgres_db
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Server=postgres_db_container;Port=5432;Database=StudentManagementDB;Username=postgres;Password=mysecretpassword;
      - ASPNETCORE_URLS=http://+:5000
    networks:
      - student_management_network

  # Blazor WebAssembly Application
  student_management_client:
    container_name: client_container
    ports:
      - "8080:8080"
    build:
      context: ./client
      dockerfile: Dockerfile
    networks:
      - student_management_network
  
  # PostgreSQL Database 
  student_management_postgres_db:
    container_name: postgres_db_container
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      PGDATA: /data/postgres
    volumes:
       - student_management_postgres_data:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - student_management_network
    restart: unless-stopped

  # PGAdmin User Interface
  student_management_pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: mysecretpassword
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - student_management_pgadmin_data:/var/lib/pgadmin

    ports:
      - "8000:80"
    networks:
      - student_management_network
    restart: unless-stopped
    
networks:
  student_management_network:
    driver: bridge

volumes:
  student_management_postgres_data:
  student_management_pgadmin_data: