@WebAPI_HostAddress = https://localhost:7120

### Get All Students
GET {{WebAPI_HostAddress}}/api/students/
Accept: application/json

### Get Student By Id
GET {{WebAPI_HostAddress}}/api/students/1
Accept: application/json

### Create a new student
POST {{WebAPI_HostAddress}}/api/students/
Content-Type: application/json

{
  "FirstName": "Emma",
  "LastName": "Bovary",
  "Email": {
    "Value": "emmabovary@gmail.com"
  },
  "BirthDate": "2004-10-01",
  "GitHubUsername": "emma-bovary"
}
